# Generated by Django 5.0.4 on 2024-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lesson_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.URLField(),
        ),
    ]
