# Generated by Django 5.0.4 on 2024-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_id_result_user_alter_test_question_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userphoto',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
