# Generated by Django 5.0.4 on 2024-08-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_userphoto_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(blank=True, null=True, upload_to='userphotos/', verbose_name='User Photo'),
        ),
    ]
