# Generated by Django 5.0.4 on 2024-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_profile_photo_user_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(blank=True, null=True, upload_to='userphoto/', verbose_name='User Photo'),
        ),
    ]
