# Generated by Django 5.0.4 on 2024-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_userphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['id'], 'verbose_name': 'Test Question', 'verbose_name_plural': 'Test Questions'},
        ),
        migrations.AddField(
            model_name='test',
            name='correct_answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4')], default='option1', help_text='Select the correct answer option.', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='option1',
            field=models.TextField(help_text='Enter option 1.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='option2',
            field=models.TextField(help_text='Enter option 2.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='option3',
            field=models.TextField(help_text='Enter option 3.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='option4',
            field=models.TextField(help_text='Enter option 4.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_img',
            field=models.ImageField(blank=True, help_text='Upload an image for the question.', null=True, upload_to='questions/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_str',
            field=models.TextField(blank=True, help_text='Enter the question text.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_subject',
            field=models.CharField(choices=[('Dasturlash', 'Dasturlash'), ('Matematika', 'Matematika'), ('Fizika', 'Fizika')], help_text='Select the subject of the question.', max_length=15),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_type1',
            field=models.CharField(choices=[('Katta sinflar', 'Katta sinflar'), ('Kichik sinflar', 'Kichik sinflar')], help_text='Select the type of question.', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='User Photo'),
        ),
    ]
